### ISSUE TITLE
Table will break with `<br>` if hrules on

### ISSUE THREAD

**Issue by chrisaga** [chrisaga/hk-pandoc-filters#1]
The LaTeX code generated by tables-rules.lua is broken when source document have a `<br>` in one cell and hrules are on.

This is due to an extra `\midrule` inserted after the end of line caused by `<br>`.

**Comment by chrisaga** [comment]
Fixed and merged in main branch

**Comment by shoaibjo** [comment]
> The LaTeX code generated by tables-rules.lua is broken when source document have a `<br>` in one cell and hrules are on.
> 
> This is due to an extra `\midrule` inserted after the end of line caused by `<br>`.


Thanks Chrisaga, recent changes solved my problem of using <br> with advance html table using colspan and rowspan.

**Comment by chrisaga** [comment]
> Thanks Chrisaga, recent changes solved my problem of using
> with advance html table using colspan and rowspan.

Glad to see this little filter could be useful ;-)
